=== BISONNL/KV20/xsd/kv20-msg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by Jan Koers (InTraffic B.V.) -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- Copyright:	Dit document is eigendom van Platform BISON onder de Stichting Connekt,-->
<!--            en wordt gepubliceerd onder de Creative Commons Licentie by-nd/3.0/nl, -->
<!--            zie http://creativecommons.org/licences/by-nd/3.0/nl                   -->
<!-- Opmerking: XSD is gebaseerd op TMI8 koppelvlak 20 versie 8.1.0.0(e)               -->
<!-- Versie:   0.1 (concept)   (16-12-2010)                                            -->
<!--           0.2 (concept)   (xx-xx-2010)                                            -->
<!-- Historie:                                                                         -->
<!--          0.1: initiele versie                                                     -->
<!--          0.2: op basis van concept (e)                                            -->
<!--          0.3: op basis van draft   (f)                                            -->
<!--          1.0: op basis van release (8.1.0.0)	                               -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tmi8="http://bison.connekt.nl/tmi8/kv20/msg" xmlns:tmi8c="http://bison.connekt.nl/tmi8/kv20/core" targetNamespace="http://bison.connekt.nl/tmi8/kv20/msg" elementFormDefault="qualified">
	<xs:import namespace="http://bison.connekt.nl/tmi8/kv20/core" schemaLocation="kv20-core.xsd"/>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- TMI KV20 messages                                                                 -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:element name="VV_TM_PUSH">
		<xs:annotation>
			<xs:documentation>Bevat door de integrator te verwerken mutaties op het geplande vervoersaanbod</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties"/>
				<xs:element name="KV20mutation" type="tmi8:KV20mutationType" maxOccurs="unbounded"/>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="tmi8c:delimiter"/>
					<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="VV_TM_REQ">
		<xs:annotation>
			<xs:documentation>Verzoek tot herzending van alle relevante mutaties op het geplande vervoersaanbod</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="VV_TM_RES">
		<xs:annotation>
			<xs:documentation>Geeft aan hoe de aan de integrator aangeboden documenten verwerkt zijn</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties" minOccurs="0"/>
				<xs:element name="ResponseCode" type="tmi8:ResponseCodeType"/>
				<xs:element name="ResponseError" type="tmi8:ResponseErrorType" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Dossiers: KV20mutation                                                            -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:complexType name="KV20mutationType">
		<xs:sequence>
			<xs:element name="KV20JOURNEY" type="tmi8:KV20journeyType"/>
			<xs:element name="KV20MUTATEJOURNEY" type="tmi8:KV20mutatejourneyType" minOccurs="0"/>
			<xs:element name="KV20MUTATEJOURNEYSTOP" type="tmi8:KV20mutatejourneystopType" minOccurs="0"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Dossiers: KV20mutationJourney                                                        -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:complexType name="KV20journeyType">
		<xs:sequence>
			<xs:element name="dataownercode" type="tmi8:dataownercodeType"/>
			<xs:element name="lineplanningnumber" type="tmi8:lineplanningnumberType"/>
			<xs:element name="journeynumber" type="tmi8:journeynumberType"/>
			<xs:element name="validfrom" type="tmi8:tmidateType"/>
			<xs:element name="validthru" type="tmi8:tmidateType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="KV20mutatejourneyType">
		<xs:annotation>
			<xs:documentation>
			 CANCEL: laat alle passages voor een rit vervallen
			 RECOVER: brengt de rit terug in de origionel staat zonder mutaties
			 ADD: gereserveerd
			 </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="timestamp" type="tmi8:tmidatetimeType"/>
			<xs:choice>
				<xs:element name="CANCEL" type="tmi8:CANCELType"/>
				<xs:element name="RECOVER" type="tmi8:RECOVERType"/>
				<xs:element name="ADD" type="tmi8:ADDType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="KV20mutatejourneystopType">
		<xs:sequence>
			<xs:element name="timestamp" type="tmi8:tmidatetimeType"/>
			<xs:choice>
				<xs:sequence minOccurs="1" maxOccurs="unbounded">
					<xs:element name="SHORTEN" type="tmi8:SHORTENType" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="CHANGEPASSTIMES" type="tmi8:CHANGEPASSTIMESType" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="CHANGEDESTINATION" type="tmi8:CHANGEDESTINATIONType" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="MUTATIONMESSAGE" type="tmi8:MUTATIONMESSAGEType" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:choice>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Mutation entities                                                                 -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:complexType name="CANCELType">
		<xs:sequence>
			<xs:sequence minOccurs="0">
				<xs:element name="reasontype" type="tmi8:sirisxcategoryType"/>
				<xs:element name="subreasontype" type="tmi8:sirisxcodeType"/>
			</xs:sequence>
			<xs:element name="reasoncontent" type="tmi8:contentType" minOccurs="0"/>
			<xs:sequence minOccurs="0">
				<xs:element name="advicetype" type="tmi8:sirisxcategoryType"/>
				<xs:element name="subadvicetype" type="tmi8:sirisxcodeType"/>
			</xs:sequence>
			<xs:element name="advicecontent" type="tmi8:contentType" minOccurs="0"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SHORTENType">
		<xs:sequence>
			<xs:element name="userstopcode" type="tmi8:codeType"/>
			<xs:element name="passagesequencenumber" type="tmi8:passagesequencenumberType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CHANGEPASSTIMESType">
		<xs:sequence>
			<xs:element name="userstopcode" type="tmi8:codeType"/>
			<xs:element name="passagesequencenumber" type="tmi8:passagesequencenumberType"/>
			<xs:element name="targetarrivaltime" type="tmi8:tmitimeType"/>
			<xs:element name="targetdeparturetime" type="tmi8:tmitimeType"/>
			<xs:element name="journeystoptype" type="tmi8:journeystoptypeType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CHANGEDESTINATIONType">
		<xs:sequence>
			<xs:element name="userstopcode" type="tmi8:codeType"/>
			<xs:element name="passagesequencenumber" type="tmi8:passagesequencenumberType"/>
			<xs:element name="destinationcode" type="tmi8:codeType" minOccurs="0"/>
			<xs:element name="destinationname50" type="tmi8:destinationname50Type"/>
			<xs:element name="destinationname16" type="tmi8:destinationname16Type"/>
			<xs:element name="destinationdetail16" type="tmi8:destinationdetail16Type" minOccurs="0"/>
			<xs:element name="destinationdisplay16" type="tmi8:destinationdisplay16Type" minOccurs="0"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MUTATIONMESSAGEType">
		<xs:sequence>
			<xs:element name="userstopcode" type="tmi8:codeType"/>
			<xs:element name="passagesequencenumber" type="tmi8:passagesequencenumberType"/>
			<xs:sequence minOccurs="0">
				<xs:element name="reasontype" type="tmi8:sirisxcategoryType"/>
				<xs:element name="subreasontype" type="tmi8:sirisxcodeType"/>
			</xs:sequence>
			<xs:element name="reasoncontent" type="tmi8:contentType" minOccurs="0"/>
			<xs:sequence minOccurs="0">
				<xs:element name="advicetype" type="tmi8:sirisxcategoryType"/>
				<xs:element name="subadvicetype" type="tmi8:sirisxcodeType"/>
			</xs:sequence>
			<xs:element name="advicecontent" type="tmi8:contentType" minOccurs="0"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RECOVERType">
		<xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ADDType">
		<xs:annotation>
			<xs:documentation>ADD is a RESERVED OPERATION</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Message property types                                                            -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:group name="MessageProperties">
		<xs:sequence>
			<xs:element name="SubscriberID" type="tmi8:SubscriberIDType"/>
			<xs:element name="Version" type="tmi8:VersionType"/>
			<xs:element name="DossierName" type="tmi8:DossierNameType"/>
			<xs:element name="Timestamp" type="tmi8:TimestampType"/>
		</xs:sequence>
	</xs:group>
	<xs:simpleType name="DossierNameType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="KV20mutation"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="VersionType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SubscriberIDType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TimestampType">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="ResponseCodeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OK"/>
			<xs:enumeration value="NOK"/>
			<xs:enumeration value="SE"/>
			<xs:enumeration value="NA"/>
			<xs:enumeration value="PE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ResponseErrorType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Common entity types                                                               -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:simpleType name="dataownercodeType">
		<xs:annotation id="E1">
			<xs:documentation xml:lang="nl">
			Een en ander bepaalt volgens BISON enumeratie E1.
			Op dit moment bekende waardes zijn:
			Vervoerders: ARR, VTN, CXX, GVB, HTM, NS, RET, SYNTUS, QBUZZ, TCR,
			Integrators:  ALGEMEEN, GOVI, RIG, SABIMOS, PRORAIL
			maar elke waarde is toegestaan
		 </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="codeType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="destinationname50Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="destinationname16Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="16"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="destinationdetail16Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="16"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="destinationdisplay16Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="16"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="passagesequencenumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="9999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="offsettimeType">
		<xs:annotation>
			<xs:documentation>
		in seconden, max +/- 36 uur
		</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:int">
			<xs:minInclusive value="-129600"/>
			<xs:maxInclusive value="+129600"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="deltatimeType">
		<xs:annotation>
			<xs:documentation>
		in seconden, max +/- 36 uur
		</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:int">
			<xs:minInclusive value="-129600"/>
			<xs:maxInclusive value="+129600"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tmitimeType">
		<xs:annotation>
			<xs:documentation>Format: HH:MM:SS / H:MM:SS accepted values : 00:00:00 - 31:59:59</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="7"/>
			<xs:maxLength value="8"/>
			<xs:pattern value="(0|1|2|3|4|5|6|7|8|9|00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|20|18|19|20|21|22|23|24|25|26|27|28|29|30|31):[012345][0123456789]:[012345][0123456789]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tmidateType">
		<xs:annotation>
			<xs:documentation>Format: YYYY-MM-DD</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:date">
			<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
			<!--
			<xs:minLength value="10"/>
			<xs:maxLength value="10"/> -->
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tmidatetimeType">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="tmibooleanType">
		<xs:restriction base="xs:boolean"/>
	</xs:simpleType>
	<xs:simpleType name="reinforcementnumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="99"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="journeynumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="lineplanningnumberType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="lagtimeType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="9999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="sirisxcategoryType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="sirisxcodeType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
			<xs:pattern value="[\d|_]+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="contentType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="journeystoptypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FIRST"/>
			<xs:enumeration value="INTERMEDIATE"/>
			<xs:enumeration value="LAST"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== BISONNL/KV20/xml/kv20-bijlage3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tmi8:VV_TM_PUSH xmlns:tmi8="http://bison.connekt.nl/tmi8/kv20/msg" xmlns:tmi8c="http://bison.connekt.nl/tmi8/kv20/core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bison.connekt.nl/tmi8/kv20/msg kv20-msg.xsd">
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Uitgewerkt voorbeeld op basis van koppelvlak 20 bijlage 3 -->
	<!-- "Voorbeeld scenario gebruik koppelvlak 20 in Utrecht"     -->
	<!-- Bevat daarnaast nog diverse uitgewerkte voorbeeld voor    -->
	<!-- o.a. ritgerelateerde vrije tekst.                         -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Start van het PUSH document -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<tmi8:SubscriberID>9292</tmi8:SubscriberID>
	<tmi8:Version>BISON 8.1.0.0</tmi8:Version>
	<tmi8:DossierName>KV20mutation</tmi8:DossierName>
	<tmi8:Timestamp>2007-10-31T11:45:21+01:00</tmi8:Timestamp>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Start uitgewerkte voorbeeld koppelvlak 20 bijlage 3       -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<tmi8:KV20mutation>
		<tmi8:KV20JOURNEY>
			<tmi8:dataownercode>CXX</tmi8:dataownercode>
			<tmi8:lineplanningnumber>L120</tmi8:lineplanningnumber>
			<tmi8:journeynumber>525</tmi8:journeynumber>
			<tmi8:validfrom>2011-06-01</tmi8:validfrom>
			<tmi8:validthru>2011-06-30</tmi8:validthru>
		</tmi8:KV20JOURNEY>
		<tmi8:KV20MUTATEJOURNEYSTOP>
			<tmi8:timestamp>2008-05-05T23:09:00+01:00</tmi8:timestamp>
			<tmi8:SHORTEN>
				<tmi8:userstopcode>101</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
			</tmi8:SHORTEN>
			<tmi8:SHORTEN>
				<tmi8:userstopcode>110</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
			</tmi8:SHORTEN>
			<tmi8:SHORTEN>
				<tmi8:userstopcode>109</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
			</tmi8:SHORTEN>
			<tmi8:SHORTEN>
				<tmi8:userstopcode>108</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
			</tmi8:SHORTEN>
			<tmi8:SHORTEN>
				<tmi8:userstopcode>107</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
			</tmi8:SHORTEN>
			<tmi8:CHANGEPASSTIMES>
				<tmi8:userstopcode>102</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
				<tmi8:targetarrivaltime>08:45:00</tmi8:targetarrivaltime>
				<tmi8:targetdeparturetime>08:45:00</tmi8:targetdeparturetime>
				<tmi8:journeystoptype>FIRST</tmi8:journeystoptype>
			</tmi8:CHANGEPASSTIMES>
			<tmi8:CHANGEDESTINATION>
				<tmi8:userstopcode>102</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
				<tmi8:destinationcode>UtrNd</tmi8:destinationcode>
				<tmi8:destinationname50>Neude</tmi8:destinationname50>
				<tmi8:destinationname16>Neude</tmi8:destinationname16>
			</tmi8:CHANGEDESTINATION>
			<tmi8:CHANGEPASSTIMES>
				<tmi8:userstopcode>103</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
				<tmi8:targetarrivaltime>08:50:00</tmi8:targetarrivaltime>
				<tmi8:targetdeparturetime>08:50:00</tmi8:targetdeparturetime>
				<tmi8:journeystoptype>INTERMEDIATE</tmi8:journeystoptype>
			</tmi8:CHANGEPASSTIMES>
			<tmi8:CHANGEDESTINATION>
				<tmi8:userstopcode>103</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
				<tmi8:destinationcode>UtrNd</tmi8:destinationcode>
				<tmi8:destinationname50>Neude</tmi8:destinationname50>
				<tmi8:destinationname16>Neude</tmi8:destinationname16>
			</tmi8:CHANGEDESTINATION>
			<tmi8:CHANGEPASSTIMES>
				<tmi8:userstopcode>104</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
				<tmi8:targetarrivaltime>08:55:00</tmi8:targetarrivaltime>
				<tmi8:targetdeparturetime>08:55:00</tmi8:targetdeparturetime>
				<tmi8:journeystoptype>INTERMEDIATE</tmi8:journeystoptype>
			</tmi8:CHANGEPASSTIMES>
			<tmi8:CHANGEDESTINATION>
				<tmi8:userstopcode>104</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
				<tmi8:destinationcode>UtrNd</tmi8:destinationcode>
				<tmi8:destinationname50>Neude</tmi8:destinationname50>
				<tmi8:destinationname16>Neude</tmi8:destinationname16>
			</tmi8:CHANGEDESTINATION>
			<tmi8:CHANGEPASSTIMES>
				<tmi8:userstopcode>105</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
				<tmi8:targetarrivaltime>09:00:00</tmi8:targetarrivaltime>
				<tmi8:targetdeparturetime>09:05:00</tmi8:targetdeparturetime>
				<tmi8:journeystoptype>INTERMEDIATE</tmi8:journeystoptype>
			</tmi8:CHANGEPASSTIMES>
			<tmi8:CHANGEDESTINATION>
				<tmi8:userstopcode>105</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
				<tmi8:destinationcode>UtrNd</tmi8:destinationcode>
				<tmi8:destinationname50>Neude</tmi8:destinationname50>
				<tmi8:destinationname16>Neude</tmi8:destinationname16>
			</tmi8:CHANGEDESTINATION>
			<tmi8:CHANGEPASSTIMES>
				<tmi8:userstopcode>106</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
				<tmi8:targetarrivaltime>09:10:00</tmi8:targetarrivaltime>
				<tmi8:targetdeparturetime>09:10:00</tmi8:targetdeparturetime>
				<tmi8:journeystoptype>LAST</tmi8:journeystoptype>
			</tmi8:CHANGEPASSTIMES>
			<tmi8:MUTATIONMESSAGE>
				<tmi8:userstopcode>105</tmi8:userstopcode>
				<tmi8:passagesequencenumber>0</tmi8:passagesequencenumber>
				<tmi8:reasoncontent>Haltes vervallen vanwege werkzaamheden</tmi8:reasoncontent>
			</tmi8:MUTATIONMESSAGE>
		</tmi8:KV20MUTATEJOURNEYSTOP>
		<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
		<!-- Einde uitgewerkte voorbeeld koppelvlak 20 bijlage 3       -->
		<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	</tmi8:KV20mutation>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Einde van het PUSH document -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
</tmi8:VV_TM_PUSH>
